import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRecoilState } from 'recoil';

import Button from '@/common/Button';
import UserFilled from 'public/icons/User/Filled.svg';
import { sampleCountState } from '../src/store';
import SampleRadio from '../components/SampleRadio';
import styles from '../styles/Home.module.css';
import { darkTheme, styled } from 'stitches.config';
import Checkbox from '@/common/Checkbox';
import { useState } from 'react';

const Home: NextPage = () => {
  const [count, setCount] = useRecoilState<number>(sampleCountState);
  const [checked, setChecked] = useState<boolean>(false);

  const ComponentPreview = ({ prefix }: { prefix?: string }) => (
    <>
      <div>
        <Button type="button" onClick={() => setCount((prev) => prev + 1)}>
          Small
        </Button>
        <Button type="button" onClick={() => setCount((prev) => prev + 1)}>
          Small
        </Button>
        <Button
          size="big"
          type="button"
          onClick={() => setCount((prev) => prev + 1)}
        >
          Big
        </Button>
        <Button disabled>Disabled</Button>
        <Button icon={<UserFilled />}>Icon Small</Button>
        <Button size="big" icon={<UserFilled />}>
          Icon Big
        </Button>
        <Button size="flat" icon={<UserFilled />}>
          Icon Flat
        </Button>
        <Link href="/donate">
          <Button>후원하기</Button>
        </Link>
      </div>
      {/* !SECTION */}

      <Checkbox
        id="demochk1"
        checked={checked}
        onChange={() => setChecked((prev) => !prev)}
        label="데모 체크박스"
      />

      {/* sample radio 컴포넌트*/}
      <SampleRadio prefix={prefix} />
    </>
  );

  const PreviewDiv = styled('div', {
    flex: 1,
    padding: 8,
    maxWidth: '100%',
    backgroundColor: '$backgroundPrimary',
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: 'flex', width: '100%' }}>
          <PreviewDiv>
            <ComponentPreview />
          </PreviewDiv>
          <PreviewDiv className={darkTheme}>
            <ComponentPreview prefix="dark" />
          </PreviewDiv>
        </div>
      </main>
    </div>
  );
};

export default Home;
